project:
  type: website
  output-dir: docs

website:
  title: "Jinyoung (Jina) Hur"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 1_work.qmd
      - href: 2_conference.qmd

  sidebar:
    - id: blog
      collapse-level: 2
      style: 'floating'
      search: true
    # toggle-position: 'center'


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left    # Moves the navigation to the left


editor: source