project:
  type: website
  output-dir: docs
  # freeze: false


website:
  title: "Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: 1_work.qmd
      - href: 2_conference.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



